# Generated by Django 5.2.4 on 2025-07-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2083)),
                ('name', models.CharField(max_length=300)),
                ('duration', models.FloatField()),
                ('serving_size', models.IntegerField(max_length=2)),
                ('ingredients', models.CharField(max_length=100)),
            ],
        ),
    ]
