# Generated by Django 5.2.4 on 2025-07-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_CookingMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_method_sub', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_sub', models.CharField(max_length=150)),
            ],
        ),
    ]
