# Generated by Django 5.2.4 on 2025-07-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0002_sub_cookingmethods_sub_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_CookingMethods',
            new_name='Sub_CookingMethod',
        ),
        migrations.RenameModel(
            old_name='Sub_Ingredients',
            new_name='Sub_Ingredient',
        ),
    ]
