# Generated by Django 5.2.4 on 2025-07-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0003_rename_sub_cookingmethods_sub_cookingmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
