# Generated by Django 5.2.4 on 2025-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0004_alter_recipe_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
