# Generated by Django 5.2.4 on 2025-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0005_alter_recipe_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.FloatField(),
        ),
    ]
