# Generated by Django 5.2.4 on 2025-07-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0006_alter_recipe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='foodtags',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.IntegerField(),
        ),
    ]
