# Generated by Django 5.2.4 on 2025-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0007_recipe_foodtags_alter_recipe_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='foodtags',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
