# Generated by Django 5.2.4 on 2025-07-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0008_alter_recipe_foodtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Ingredient',
            new_name='SubstituteIngredients',
        ),
        migrations.RenameField(
            model_name='substituteingredients',
            old_name='ingredient_sub',
            new_name='substitute_ingredients',
        ),
    ]
