# Generated by Django 5.2.4 on 2025-07-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0009_rename_sub_ingredient_substituteingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubstituteIngredients',
            new_name='SubstituteIngredient',
        ),
    ]
