# Generated by Django 5.2.4 on 2025-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0010_rename_substituteingredients_substituteingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteCookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_cooking_method', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_CookingMethod',
        ),
    ]
