# Generated by Django 5.2.4 on 2025-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0011_substitutecookingmethod_delete_sub_cookingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutecookingmethod',
            name='emissions',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='substitutecookingmethod',
            name='fuel',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='emissions',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='nutritional_value',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='substitutecookingmethod',
            name='substitute_cooking_method',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='substituteingredient',
            name='substitute_ingredients',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
