# Generated by Django 5.2.4 on 2025-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0012_substitutecookingmethod_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_appliance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DietOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.CharField(max_length=300)),
                ('vegan', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cookingmethod', models.CharField(max_length=100)),
                ('CO2', models.FloatField()),
                ('NO2', models.FloatField()),
                ('PM25', models.FloatField()),
                ('PM10', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GridAnalysi',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=300)),
                ('optimal_time_of_day', models.IntegerField()),
                ('carbon_intensity', models.CharField(max_length=100)),
                ('regional_factor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cooktype', models.CharField(max_length=100)),
                ('VITC', models.FloatField()),
                ('VITB', models.FloatField()),
                ('VITK', models.FloatField()),
                ('ANTIOX', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStepAnalysi',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('step_1', models.CharField(max_length=5000)),
                ('step_2', models.CharField(max_length=5000)),
                ('step_3', models.CharField(max_length=5000)),
                ('step_4', models.CharField(max_length=5000)),
                ('step_5', models.CharField(max_length=5000)),
                ('step_6', models.CharField(default='null', max_length=5000)),
                ('step_7', models.CharField(default='null', max_length=5000)),
                ('step_8', models.CharField(default='null', max_length=5000)),
                ('step_9', models.CharField(default='null', max_length=5000)),
                ('step_10', models.CharField(default='null', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Timeofday',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='colour_code_emissions',
            field=models.CharField(default='?', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='colour_code_nutrition',
            field=models.CharField(default='?', max_length=10),
        ),
    ]
