# Generated by Django 5.2.4 on 2025-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0013_cookingappliance_cookingmethod_dietoption_emissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substituteingredient',
            old_name='substitute_ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='substituteingredient',
            old_name='emissions',
            new_name='ingredient_emissions',
        ),
        migrations.RenameField(
            model_name='substituteingredient',
            old_name='nutritional_value',
            new_name='ingredient_nutritional_value',
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='substitute_ingredient',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='substitute_ingredient_emissions',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='substitute_ingredient_nutritional_value',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='substituteingredient',
            name='substitute_ingredient_type',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipestepanalysi',
            name='step_3',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipestepanalysi',
            name='step_4',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipestepanalysi',
            name='step_5',
            field=models.CharField(default='null', max_length=5000),
        ),
    ]
