# Generated by Django 5.2.4 on 2025-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0014_rename_substitute_ingredients_substituteingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='step_1',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_10',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_2',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_3',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_4',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_5',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_6',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_7',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_8',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_9',
            field=models.CharField(default='null', max_length=5000),
        ),
    ]
