# Generated by Django 5.2.4 on 2025-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0015_recipe_step_1_recipe_step_10_recipe_step_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='duration',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_prep',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
