# Generated by Django 5.2.4 on 2025-07-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0016_remove_recipe_duration_recipe_cooking_prep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_name',
        ),
    ]
