# Generated by Django 5.2.4 on 2025-07-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0017_rename_location_location_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
