# Generated by Django 5.2.4 on 2025-07-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0018_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeStepAnalysi',
            new_name='RecipeStep',
        ),
    ]
