# Generated by Django 5.2.4 on 2025-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0019_rename_recipestepanalysi_recipestep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_prep',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
