# Generated by Django 5.2.4 on 2025-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0024_alter_cookingmethod_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingmethod',
            name='CO2',
            field=models.CharField(default='0'),
        ),
    ]
