# Generated by Django 5.2.4 on 2025-07-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0025_alter_cookingmethod_co2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingmethod',
            name='CO2',
        ),
    ]
