# Generated by Django 5.2.4 on 2025-07-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0026_remove_cookingmethod_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingmethod',
            name='CO2',
            field=models.IntegerField(default='0'),
        ),
    ]
