# Generated by Django 5.2.4 on 2025-07-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0032_alter_cookingmethod_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingappliance',
            name='CO2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookingmethod',
            name='nutrition_loss',
            field=models.IntegerField(default=0),
        ),
    ]
