# Generated by Django 5.2.4 on 2025-07-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0033_cookingappliance_co2_cookingmethod_nutrition_loss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookingMethod',
        ),
    ]
