# Generated by Django 5.2.4 on 2025-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0034_delete_cookingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_method', models.CharField(max_length=100)),
                ('CO2', models.IntegerField(default=0)),
                ('nutrition_loss', models.IntegerField(default=0)),
            ],
        ),
    ]
