# Generated by Django 5.2.4 on 2025-07-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0035_cookingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_10',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_8',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step_9',
        ),
    ]
