# Generated by Django 5.2.4 on 2025-07-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0036_remove_recipe_step_1_remove_recipe_step_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='recipe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='steps', to='recipestepbystep.recipe'),
        ),
    ]
