# Generated by Django 5.2.4 on 2025-07-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0037_alter_recipestep_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='steps', to='recipestepbystep.recipe'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
