# Generated by Django 5.2.4 on 2025-07-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0038_recipestep_recipe_alter_recipestep_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='recipe_name',
        ),
    ]
