# Generated by Django 5.2.4 on 2025-07-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0039_remove_recipestep_recipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubstituteIngredient',
            new_name='Ingredient',
        ),
    ]
