# Generated by Django 5.2.4 on 2025-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0040_rename_substituteingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_emissions',
            new_name='emissions',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_nutritional_value',
            new_name='nutritional_value',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='substitute_ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='substitute_ingredient_emissions',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='substitute_ingredient_nutritional_value',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='substitute_ingredient_type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='substitutes',
            field=models.ManyToManyField(
                blank=True, related_name='substituted_by', to='recipestepbystep.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
