# Generated by Django 5.2.4 on 2025-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0041_rename_ingredient_emissions_ingredient_emissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='recipes', to='recipestepbystep.ingredient'),
        ),
    ]
