# Generated by Django 5.2.4 on 2025-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0042_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=150)),
                ('nutritional_value', models.CharField(
                    default='none', max_length=100)),
                ('emissions', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='substitutes',
            field=models.ManyToManyField(
                blank=True, related_name='substituted_by', to='recipestepbystep.ingredientsubstitutes'),
        ),
    ]
