# Generated by Django 5.2.4 on 2025-07-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0043_ingredientsubstitutes_alter_ingredient_substitutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='emissions',
            new_name='emissions_key',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='nutritional_value',
            new_name='nutritional_value_key',
        ),
    ]
