# Generated by Django 5.2.4 on 2025-07-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0044_rename_emissions_ingredient_emissions_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsubstitutes',
            old_name='emissions',
            new_name='emissions_key',
        ),
        migrations.RenameField(
            model_name='ingredientsubstitutes',
            old_name='nutritional_value',
            new_name='nutritional_value_key',
        ),
    ]
