# Generated by Django 5.2.4 on 2025-07-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0045_rename_emissions_ingredientsubstitutes_emissions_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='emissions',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutritional_value',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredientsubstitutes',
            name='emissions',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredientsubstitutes',
            name='nutritional_value',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='emissions_key',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nutritional_value_key',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredientsubstitutes',
            name='emissions_key',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredientsubstitutes',
            name='nutritional_value_key',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
