# Generated by Django 5.2.4 on 2025-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0046_ingredient_emissions_ingredient_nutritional_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nutritional_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredientsubstitutes',
            name='emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredientsubstitutes',
            name='nutritional_value',
            field=models.FloatField(default=0.0),
        ),
    ]
