# Generated by Django 5.2.4 on 2025-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0047_alter_ingredient_emissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_prep',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='colour_code_emissions',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='colour_code_nutrition',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='foodtags',
            field=models.CharField(default='---', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='---', max_length=2083),
        ),
    ]
