# Generated by Django 5.2.4 on 2025-07-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0048_remove_recipe_cooking_prep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingappliance',
            name='CO2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='CO2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cookingmethod',
            name='nutrition_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
