# Generated by Django 5.2.4 on 2025-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep',
         '0049_alter_cookingappliance_co2_alter_cookingmethod_co2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_emission_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeofday',
            name='emission_multiplier',
            field=models.FloatField(default=0.0),
        ),
    ]
