# Generated by Django 5.2.4 on 2025-07-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0050_location_location_emission_factor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietOption',
        ),
        migrations.DeleteModel(
            name='Emissions',
        ),
        migrations.DeleteModel(
            name='GridAnalysi',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
