# Generated by Django 5.2.4 on 2025-08-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0051_delete_dietoption_delete_emissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='colour_code_emissions',
            new_name='emissions_key',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='colour_code_nutrition',
            new_name='nutritional_value_key',
        ),
    ]
