# Generated by Django 5.2.4 on 2025-08-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0052_rename_colour_code_emissions_recipe_emissions_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredientsubstitutes',
            old_name='ingredient',
            new_name='name',
        ),
    ]
