# Generated by Django 5.2.4 on 2025-08-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0053_rename_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps2', to='recipestepbystep.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeStep2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipestepbystep.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
