# Generated by Django 5.2.4 on 2025-08-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0054_alter_recipestep_recipe_recipestep2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_10',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_2',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_3',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_4',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_5',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_6',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_7',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_8',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_9',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='content',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='order',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='recipestepbystep.recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeStep2',
        ),
    ]
