# Generated by Django 5.2.4 on 2025-08-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0055_alter_recipestep_options_remove_recipestep_step_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='cookingappliance',
            old_name='cooking_appliance',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cookingmethod',
            old_name='cooking_method',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='cooking_appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_appliance', to='recipestepbystep.cookingappliance'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='cooking_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_methods', to='recipestepbystep.cookingmethod'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='ventilation',
            field=models.IntegerField(default='0'),
        ),
    ]
