# Generated by Django 5.2.4 on 2025-08-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipestepbystep', '0056_nutrient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientSubstitutes',
            new_name='IngredientSubstitute',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='nutrients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='recipestepbystep.nutrient'),
        ),
    ]
